
CREATE TABLE days(dayID INT PRIMARY KEY,day VARCHAR(255))
CREATE TABLE waiters(waiterID INT PRIMARY KEY,name VARCHAR(255))
CREATE TABLE admin(dayID INT,name VARCHAR(255), FOREIGN KEY(dayID) REFERENCES days(dayID));
